version: '3.4'

services:
  web:
    image: web-php-dev:latest
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - MONGO_HOST=mongodb://mongodb
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html/
      - ./vendor:/var/www/html/vendor
    depends_on:
      - mongo
  mongo:
    image: mongo:3-stretch
    container_name: mongodb