version: '3.4'

services:
  web:
    image: web-php-dev:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=mongodb://mongodb
    ports:
      - "8080:80"
    depends_on:
      - mongo
  mongo:
    image: mongo:3-stretch
    container_name: mongodb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: