version: '3.4'

services:
  web:
    image: web-php-dev:latest
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
  mongo:
    image: mongo:3-stretch
    container_name: mongodb